version: '2'

services:

  redmine:
    image: ink/redmine
    container_name: redmine_inki
    hostname: 'redmine'
    ports:
      - 10095:3000
    environment:
      REDMINE_DB_MYSQL: mariadb_redmine
      REDMINE_DB_PASSWORD: secr3t
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.1
    container_name: mariadb_redmine
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: secr3t
    volumes:
      - ./redminedb-init.d:/docker-entrypoint-initdb.d
    # - ./database:/var/lib/mysql    
    restart: always

  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=-
    container_name: dnsmasq
    cap_add:
      - NET_ADMIN
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp

  web:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=galaxy.docker
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./app.conf:/etc/nginx/conf.d/app.conf

  proxy:
    image: jwilder/nginx-proxy
    environment:
      - DNSDOCK_ALIAS=galaxy.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- ./nginx-proxy-certs:/etc/nginx/certs:ro
      #- ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
