version: '2'

services:

  redmine:
    image: ink/redmine
    container_name: redmine_inki
    ports:
      - 10095:3000
    environment:
      REDMINE_DB_MYSQL: mariadb_redmine
      REDMINE_DB_PASSWORD: secr3t
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.1
    container_name: mariadb_redmine
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: secr3t
    volumes:
      - ./redminedb-init.d:/docker-entrypoint-initdb.d
    # - ./database:/var/lib/mysql    
    restart: always
